INSERT INTO category (description) VALUES ('Protein');
INSERT INTO category (description) VALUES ('Pre-Workout');
INSERT INTO category (description) VALUES ('Amino acid');
INSERT INTO category (description) VALUES ('Creatine');
INSERT INTO category (description) VALUES ('Vitamin');
INSERT INTO category (description) VALUES ('Gainer');
INSERT INTO category (description) VALUES ('Fat burner');
INSERT INTO user (email, first_name, last_name, password, role) VALUES ('imrelori@hotmail.hu', 'Lorant', 'Imre', 'root', 'admin');
INSERT INTO user (role) VALUES ('guest');
INSERT INTO user (role) VALUES ('registered user');